### ISSUE TITLE
Error in uniroot

### ISSUE THREAD

**Issue by susheelbhanu** [microbiome/microbiome#138]
Hi all, 

Thanks for a great package. I am trying to get the diversity metrics from a `phyloseq` object, and keep getting the following error

commands:
```
otu.file <- "ZF_full_ASV.csv"
tax.file <- "ZF_full_taxonomy.csv"
metadata.file <- "ZF_full_metadata.csv"

pseq <- read_csv2phyloseq(
  otu.file = otu.file,
  taxonomy.file = tax.file,
  metadata.file = metadata.file,
  sep = ",")
tab <- microbiome::alpha(pseq, index = "all")
```
```
Error in uniroot(d1fun, c(1, 50), extendInt = "upX", S = S, N = N, ...) : 
  did not succeed extending the interval endpoints for f(lower) * f(upper) <= 0
In addition: Warning message:
In log(1 + N/x) : NaNs produced
```

It seems to work though if I chose `index="Shannon"` or `index=Chao1`, whereas it fails on `all`. I'm attaching the `.txt` files here for reference 'cos I can't upload the CSVs. . Thank you for your help!
-Susheel

[ZF_full_metadata.txt](https://github.com/microbiome/microbiome/files/4775103/ZF_full_metadata.txt)
[ZF_full_taxonomy.txt](https://github.com/microbiome/microbiome/files/4775104/ZF_full_taxonomy.txt)
[ZF_full_ASV.txt](https://github.com/microbiome/microbiome/files/4775101/ZF_full_ASV.txt)

**Comment by antagomir** [comment]
Should work now. May return few NAs for Fisher's alpha because it is only defined for cases with mover than one non-zero value in the abundance.

**Comment by susheelbhanu** [comment]
Thank you. So, I'm assuming i'll need to do a clean install again?

**Comment by antagomir** [comment]
Yes, from github the version 2.1.25 should do the trick

**Comment by susheelbhanu** [comment]
Great, thanks a lot @antagomir

**Comment by antoine4ucsd** [comment]
I have the same error...
I am trying to update my package but still get 1.12.0

``
Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.3 (2020-10-10)
Installing package(s) 'microbiome'
trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/macosx/contrib/4.0/microbiome_1.12.0.tgz'
``
any suggestions?
thank you for this great package!

**Comment by antagomir** [comment]
Could you use the latest Github devel version?

`devtools::install_github("microbiome/microbiome")`

**Comment by antoine4ucsd** [comment]
Indeed. Good idea! I will give it a try
Thank you

--
a

**Comment by dinhe878** [comment]
Hi @antagomir, I just installed the latest GitHub version but got the same error!
```
> devtools::install_github("microbiome/microbiome")
Downloading GitHub repo microbiome/microbiome@HEAD
✓  checking for file ‘/private/var/folders/8k/0vmy4q3x7vb5dgzw8zjp5tjr0000gn/T/RtmpPwOfSe/remotesde62854285c/microbiome-microbiome-3e3b035/DESCRIPTION’ ...
─  preparing ‘microbiome’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘microbiome_1.13.9.tar.gz’
   
Installing package into ‘/usr/local/lib/R/4.0/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘microbiome’ ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (microbiome)
> library("microbiome")
> GAGA_ampSeq.alphadiv <- alpha(GAGA_ampSeq.physeq.rarefy, index = "all")
Observed richness
Other forms of richness
Diversity
Error in uniroot(d1fun, c(1, 50), extendInt = "upX", S = S, N = N, ...) : 
  did not succeed extending the interval endpoints for f(lower) * f(upper) <= 0
In addition: Warning message:
In log(1 + N/x) : NaNs produced

```
Thanks a lot for the help!

**Comment by antagomir** [comment]
Can you send output of R sessionInfo()

**Comment by dinhe878** [comment]
```
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin20.3.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /usr/local/Cellar/r/4.0.5/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] DT_0.18                     microbiomeutilities_1.00.16 microbiome_1.13.9          
 [4] phyloseq_1.34.0             qiime2R_0.99.5              ggpubr_0.4.0               
 [7] RColorBrewer_1.1-2          ggplot2_3.3.3               dplyr_1.0.5                
[10] data.table_1.14.0          

loaded via a namespace (and not attached):
  [1] readxl_1.3.1        backports_1.2.1     Hmisc_4.5-0         plyr_1.8.6          igraph_1.2.6       
  [6] splines_4.0.5       crosstalk_1.1.1     usethis_2.0.1       digest_0.6.27       foreach_1.5.1      
 [11] htmltools_0.5.1.1   fansi_0.4.2         magrittr_2.0.1      checkmate_2.0.0     memoise_2.0.0      
 [16] cluster_2.1.2       openxlsx_4.2.3      remotes_2.3.0       Biostrings_2.58.0   prettyunits_1.1.1  
 [21] jpeg_0.1-8.1        colorspace_2.0-0    ggrepel_0.9.1       haven_2.4.0         xfun_0.22          
 [26] callr_3.7.0         crayon_1.4.1        jsonlite_1.7.2      survival_3.2-10     iterators_1.0.13   
 [31] ape_5.4-1           glue_1.4.2          gtable_0.3.0        zlibbioc_1.36.0     XVector_0.30.0     
 [36] car_3.0-10          pkgbuild_1.2.0      Rhdf5lib_1.12.1     BiocGenerics_0.36.1 abind_1.4-5        
 [41] scales_1.1.1        pheatmap_1.0.12     DBI_1.1.1           rstatix_0.7.0       Rcpp_1.0.6         
 [46] progress_1.2.2      htmlTable_2.1.0     foreign_0.8-81      Formula_1.2-4       stats4_4.0.5       
 [51] truncnorm_1.0-8     htmlwidgets_1.5.3   ellipsis_0.3.1      pkgconfig_2.0.3     NADA_1.6-1.1       
 [56] farver_2.1.0        nnet_7.3-15         utf8_1.2.1          tidyselect_1.1.0    labeling_0.4.2     
 [61] rlang_0.4.10        reshape2_1.4.4      munsell_0.5.0       cellranger_1.1.0    tools_4.0.5        
 [66] cachem_1.0.4        cli_2.4.0           generics_0.1.0      ade4_1.7-16         devtools_2.4.0     
 [71] broom_0.7.6         biomformat_1.18.0   stringr_1.4.0       fastmap_1.1.0       yaml_2.2.1         
 [76] processx_3.5.1      knitr_1.32          fs_1.5.0            zip_2.1.1           purrr_0.3.4        
 [81] nlme_3.1-152        compiler_4.0.5      rstudioapi_0.13     curl_4.3            png_0.1-7          
 [86] testthat_3.0.2      ggsignif_0.6.1      zCompositions_1.3.4 tibble_3.1.1        stringi_1.5.3      
 [91] ps_1.6.0            desc_1.3.0          forcats_0.5.1       lattice_0.20-41     Matrix_1.3-2       
 [96] vegan_2.5-7         ggsci_2.9           permute_0.9-5       multtest_2.46.0     vctrs_0.3.7        
[101] pillar_1.6.0        lifecycle_1.0.0     rhdf5filters_1.2.0  R6_2.5.0            latticeExtra_0.6-29
[106] gridExtra_2.3       rio_0.5.26          IRanges_2.24.1      sessioninfo_1.1.1   codetools_0.2-18   
[111] MASS_7.3-53.1       assertthat_0.2.1    pkgload_1.2.1       rhdf5_2.34.0        rprojroot_2.0.2    
[116] withr_2.4.2         S4Vectors_0.28.1    mgcv_1.8-35         parallel_4.0.5      hms_1.0.0          
[121] grid_4.0.5          rpart_4.1-15        gghalves_0.1.1      tidyr_1.1.3         carData_3.0-4      
[126] Rtsne_0.15          Biobase_2.50.0      base64enc_0.1-3    
```

**Comment by antagomir** [comment]
You code does not show what is `GAGA_ampSeq.physeq.rarefy`. Is this problem reproducible with some of the ready made demo data sets in the package? (dietswap, atlas1006..)

**Comment by dinhe878** [comment]
Thanks! In fact, the dietswap works fine. Could you hint what might cause the issue? Here is my data (rarefy at size of 7000):
```
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 14889 taxa and 237 samples ]
sample_data() Sample Data:       [ 237 samples by 5 sample variables ]
tax_table()   Taxonomy Table:    [ 14889 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 14889 tips and 14841 internal nodes ]

```

**Comment by dinhe878** [comment]
Also, when I do 
`dietswap.div <- alpha(dietswap.rarefy, index = "diversity")`
It returns an empty df. 

What are the specific names for the indices?

**Comment by antagomir** [comment]
This example does not show how `dietswap.rarefy` was created. 

Did you check help(alpha)? It says: "All indicators from the richness, diversity, evenness, dominance,
     and rarity functions are available." -> you can check those functions for the available indices.

**Comment by dinhe878** [comment]
So I tried 
```
> dietswap.div <- alpha(dietswap, index = "diversity")
Observed richness
Other forms of richness
Diversity
Evenness
Dominance
Rarity
> dietswap.div
data frame with 0 columns and 0 rows
> dietswap.eve <- alpha(dietswap, index = "evenness")
Observed richness
Other forms of richness
Diversity
Evenness
Dominance
Rarity
> dietswap.eve
data frame with 0 columns and 0 rows
> dietswap.dom <- alpha(dietswap, index = "dominance")
Observed richness
Other forms of richness
Diversity
Evenness
Dominance
Rarity
> dietswap.dom
data frame with 0 columns and 0 rows
> dietswap.rich <- alpha(dietswap, index = "richness")
Observed richness
Other forms of richness
Diversity
Evenness
Dominance
Rarity
> dietswap.rich
data frame with 0 columns and 0 rows
> dietswap.rari <- alpha(dietswap, index = "rarity")
Observed richness
Other forms of richness
Diversity
Evenness
Dominance
Rarity
> dietswap.rari
data frame with 0 columns and 0 rows
```

None returned any values

**Comment by dinhe878** [comment]
So far only `dietswap.shan <- alpha(dietswap, index = "shannon")` returned values
```
> head(dietswap.shan)
         diversity_shannon
Sample-1          2.940698
Sample-2          2.822472
Sample-3          2.407962
Sample-4          2.992482
Sample-5          2.106022
Sample-6          2.071136

```

**Comment by antagomir** [comment]
Hi - look at index names in

help(richness)
help(dominance)
etc.

**Comment by dinhe878** [comment]
Thanks! I think that I zeroed in to the source of my problem 
```
GAGA_ampSeq.fisher <- alpha(GAGA_ampSeq.physeq.rarefy, index = 'fisher')
Observed richness
Other forms of richness
Diversity
Error in uniroot(d1fun, c(1, 50), extendInt = "upX", S = S, N = N, ...) : 
  did not succeed extending the interval endpoints for f(lower) * f(upper) <= 0
In addition: Warning message:
In log(1 + N/x) : NaNs produced

```
But I still don't know what is the problem with my data.... 

Any idea?

**Comment by antagomir** [comment]
This would perhaps require checking the object that causes the error. Do you have taxa or samples where all entries are 0?

**Comment by dinhe878** [comment]
I found a relevant post that reported the same issue: https://github.com/joey711/phyloseq/issues/1009 

It seems that the fisher.alpha() from vegan may be causing this issue?

**Comment by antagomir** [comment]
Right. Then the issue shuold be addressed to phyloseq package.

You could also have a look at the emerging TreeSummarizedExperiment ecosystem (microbiome.github.io) for alternatives.

**Comment by dinhe878** [comment]
Thanks @antagomir for the suggestion. I've also reported an issue to vegan repo and hopefully got some answer soon.
