### ISSUE TITLE
global() error

### ISSUE THREAD

**Issue by RachelRodgers** [microbiome/microbiome#61]
Error received when trying to run global() on phyloseq object:
`Error in colSums(xcomp[cm, ]) : 'x' must be an array of at least two dimensions`

I think I traced down the problem.  It seems that colSums() fails on line 25 of core_abundance.R when cm has a length of exactly one.

Here's the problematic section:

    if (ncol(xcomp) > 1) {
        colSums(xcomp[cm, ])
    } else {
        sum(xcomp[cm, ])
    }

I noticed that you're checking the number of columns in xcomp.  Should you also make sure that the length of cm is greater than one before calling colSums()?

**Comment by antagomir** [comment]
Thanks ! Should be fixed now in the github repo, version 1.1.10001.

**Comment by RachelRodgers** [comment]
Hi,

Thanks for the quick reply.  However I don't think I made the problem clear.  The issue here is that if the length of xcomp is exactly equal to 1 (that is, only one sample/taxon was selected), then colSums will fail.  I think you should write something like:

```# Pick the core and calculate abundance
    if (ncol(xcomp) > 1 & length(cm) != 1) {
      colSums(xcomp[cm, ])
    } else {
      sum(xcomp[cm, ])
    }
```
 
In the case where xcomp is exactly 1, you will still get a value calculated for the core abundance index.  I have attached a phyloseq object, and an R script where you can see how the core_abundance function behaves on this object with the way it is currently written, and with my suggested fix.

Please note that I'm not very familiar with these types of analyses, and so if this particular situation (xcomp ==1) will lead to erroneous results, maybe an error message would be warranted here instead.

Thanks so much!

[microbiome_bugTest.zip](https://github.com/microbiome/microbiome/files/1447027/microbiome_bugTest.zip)
